server:
  port: 9089
#MINIO
oss:
  name: minio
  accessKey: admin
  secretKey: admin123456
  bucketName: test
  endpoint: http://192.168.126.140:9000
  fileExt: png,jpg,jpeg,pdf
spring:
  redis:
    host: 192.168.126.140
    port: 6379
    password: 123456
    database: 0